### ISSUE TITLE
Plugin does not work in Yosemite. 

### ISSUE THREAD

**Issue by jaepage** [scottmartin/speak-selected-text-sublime#6]
I have two machines, one running Mavericks (Mac OS X v 9.5) and the other running Yosemite (v 10.2). Both have Sublime Text 3. 

The plugin works fine on the Mavericks machine, but not on the Yosemite machine. The repo has been cloned to `~/Library/Application Support/Sublime Text 3/`, and both machines have the same user key binding created. The Yosemite machine shows no sign of the plugin in the Sublime app's control-click contextual dialog nor in the cmd-shift-p package dialog.

**Comment by scottmartin** [comment]
I'm really sorry to hear it's not working for you. This was written for Sublime Text 2. I switched to Atom shortly after it was announced and have not used Sublime Text 3 at all. So far Atom has completely avoided this issue and has 95% of what I liked about Sublime Text. The Atom devs have also shown direct interest in making sure that we don't have this text to speech issue over there: https://discuss.atom.io/t/apples-text-to-speech-stopped-working-in-a-recent-update/11518.

I don't even have Sublime Text installed anymore, so I can't even test anything out for you. I know it's not the answer you were hoping for but I would really check out Atom and see if it works for your needs. http://atom.io.
