### ISSUE TITLE
Plans to support Sublime Text 3 ?

### ISSUE THREAD

**Issue by fabswt** [scottmartin/speak-selected-text-sublime#7]
Hi,
Great idea of a plugin, it' too bad TTS doesn't behave properly in Sublime.

The title says it all: are there plans to port this plugin to Sublime Text 3?

Best –
Fabien

**Comment by scottmartin** [comment]
I'm really sorry, but no. I don't own version 3. I switched to GitHub's Atom shortly after it came out, and I've had no problems using text to speech with it. https://atom.io

You can read this thread for more information. https://github.com/scottmartin/speak-selected-text-sublime/issues/3
